# Generated by Django 6.0.3 on 2026-04-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financerecord',
            name='description',
            field=models.TextField(blank=True, help_text='Notes or description for the entry', null=True),
        ),
    ]
